--this script initiates db for h2 db (used in test profile)
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'john@domain.com', 'John', 'Steward')
insert into user (id, account_status, email, first_name) values (null, 'NEW', 'tracy@domain.com', 'Brian')
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'jan@yahoo.com', 'Jan', 'Kowalski')
insert into user (id, account_status, email, first_name, last_name) values (null, 'REMOVED', 'dean@domain.com', 'Maire', 'Yorke')
insert into user (id, account_status, email, first_name, last_name) values (null, 'CONFIRMED', 'Sam@domain.com', 'Colin', 'Greenwood')
insert into blog_post (user_id, entry, id) values (1, 'CONTENT_CONTENT_CONTENT', null)
insert into blog_post (user_id, entry, id) values (1, 'CONTENT_CONTENT_CONTENT', null)